//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProjetFilm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drapeau
    {
        public int Id { get; set; }
        public string CheminImage { get; set; }
    
        public virtual Pays Pays { get; set; }
    }
}
